name: finzobilling
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.13.1
  fl_chart: ^1.1.1
  flutter_speed_dial: ^7.0.0
  share_plus: ^12.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  rxdart: ^0.28.0
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  url_launcher: ^6.2.5
  http: ^1.5.0
  permission_handler: ^12.0.1
  csv: ^6.0.0
  device_info_plus: ^12.1.0
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  uuid: ^4.3.3
  package_info_plus: ^9.0.0
  firebase_analytics: ^12.0.3
  firebase_crashlytics: ^5.0.3
  firebase_performance: ^0.11.1+1
  google_sign_in: ^6.2.0
  smooth_page_indicator: ^1.2.1
  mobile_scanner: ^5.1.1
  firebase_messaging: ^16.0.3
  google_generative_ai: ^0.4.7
  web_socket_channel: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  remove_alpha_ios: true
